export enum actionTypes {
  // AUTH
  AUTH_SUCCESS = '@Auth/AUTH_SUCCESS'
  ,AUTH_LOGOUT = '@Auth/AUTH_LOGOUT'
  ,AUTH_CONFIG = '@Auth/AUTH_CONFIG'

  // RATES
  ,FETCH_RATES_SUCCESS = '@Rates/FETCH_RATES_SUCCESS'
  ,FETCH_RATES_ERROR = '@Rates/FETCH_RATES_ERROR'
  ,FETCH_RATES_DATA = '@Rates/FETCH_RATES_DATA'
  ,FETCH_RATES_QUOTES = '@Rates/FETCH_RATES_QUOTES'

  // SELECTED
  ,ADD_SELECTED = '@Selected/ADD_SELECTED'
  ,ADD_SELECTED_ERROR = '@Selected/ADD_SELECTED_ERROR'
  ,CLEAR_SELECTED_DATA = '@Selected/CLEAR_SELECTED_DATA'

  // CONFIG
  ,FETCH_CONFIG_SUCCESS = '@Config/FETCH_CONFIG_SUCCESS'
  ,FETCH_CONFIG_ERROR = '@Config/FETCH_CONFIG_ERROR'
  ,FETCH_CONFIG_DATA = '@Config/FETCH_CONFIG_DATA'
  ,FETCH_CONFIG_QUOTES = '@Config/FETCH_CONFIG_QUOTES'
  ,POST_CONFIG_DATA = '@Config/POST_CONFIG_DATA'
  ,PATCH_CONFIG_DATA = '@Config/PATCH_CONFIG_DATA'
  ,CLEAR_CONFIG_DATA = '@Config/CLEAR_CONFIG_DATA'

}

