export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS'
export const FETCH_RATES_ERROR = 'FETCH_RATES_ERROR'
export const FETCH_RATES_DATA = 'FETCH_RATES_DATA'
export const FETCH_RATES_QUOTES = 'FETCH_RATES_QUOTES'

export const ADD_SELECTED = 'ADD_SELECTED'
export const ADD_SELECTED_ERROR = 'ADD_SELECTED_ERROR'

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS'
export const FETCH_CONFIG_ERROR = 'FETCH_CONFIG_ERROR'
export const FETCH_CONFIG_DATA = 'FETCH_CONFIG_DATA'
export const FETCH_CONFIG_QUOTES = 'FETCH_CONFIG_QUOTES'