export const options = [
  { value: "AED", label: "AED"}, 
  { value: "AFN", label: "AFN"},
  { value: "ALL", label: "ALL"},
  { value: "AMD", label: "AMD"},
  { value: "ANG", label: "ANG"},
  { value: "AOA", label: "AOA"},
  { value: "ARS", label: "ARS"},
  { value: "AUD", label: "AUD"},
  { value: "AWG", label: "AWG"},
  { value: "AZN", label: "AZN"},
  { value: "BAM", label: "BAM"},
  { value: "BBD", label: "BBD"},
  { value: "BDT", label: "BDT"},
  { value: "BGN", label: "BGN"},
  { value: "BHD", label: "BHD"},
  { value: "BIF", label: "BIF"},
  { value: "BMD", label: "BMD"},
  { value: "BND", label: "BND"},
  { value: "BOB", label: "BOB"},
  { value: "BRL", label: "BRL"},
  { value: "BSD", label: "BSD"},
  { value: "BTC", label: "BTC"},
  { value: "BTN", label: "BTN"},
  { value: "BWP", label: "BWP"},
  { value: "BYN", label: "BYN"},
  { value: "BZD", label: "BZD"},
  { value: "CAD", label: "CAD"},
  { value: "CDF", label: "CDF"},
  { value: "CHF", label: "CHF"},
  { value: "CLF", label: "CLF"},
  { value: "CLP", label: "CLP"},
  { value: "CNH", label: "CNH"},
  { value: "CNY", label: "CNY"},
  { value: "COP", label: "COP"},
  { value: "CRC", label: "CRC"},
  { value: "CUC", label: "CUC"},
  { value: "CUP", label: "CUP"},
  { value: "CVE", label: "CVE"},
  { value: "CZK", label: "CZK"},
  { value: "DJF", label: "DJF"},
  { value: "DKK", label: "DKK"},
  { value: "DOP", label: "DOP"},
  { value: "DZD", label: "DZD"},
  { value: "EGP", label: "EGP"},
  { value: "ERN", label: "ERN"},
  { value: "ETB", label: "ETB"},
  { value: "EUR", label: "EUR"},
  { value: "FJD", label: "FJD"},
  { value: "FKP", label: "FKP"},
  { value: "GBP", label: "GBP"},
  { value: "GEL", label: "GEL"},
  { value: "GGP", label: "GGP"},
  { value: "GHS", label: "GHS"},
  { value: "GIP", label: "GIP"},
  { value: "GMD", label: "GMD"},
  { value: "GNF", label: "GNF"},
  { value: "GTQ", label: "GTQ"},
  { value: "GYD", label: "GYD"},
  { value: "HKD", label: "HKD"},
  { value: "HNL", label: "HNL"},
  { value: "HRK", label: "HRK"},
  { value: "HTG", label: "HTG"},
  { value: "HUF", label: "HUF"},
  { value: "IDR", label: "IDR"},
  { value: "ILS", label: "ILS"},
  { value: "IMP", label: "IMP"},
  { value: "INR", label: "INR"},
  { value: "IQD", label: "IQD"},
  { value: "IRR", label: "IRR"},
  { value: "ISK", label: "ISK"},
  { value: "JEP", label: "JEP"},
  { value: "JMD", label: "JMD"},
  { value: "JOD", label: "JOD"},
  { value: "JPY", label: "JPY"},
  { value: "KES", label: "KES"},
  { value: "KGS", label: "KGS"},
  { value: "KHR", label: "KHR"},
  { value: "KMF", label: "KMF"},
  { value: "KPW", label: "KPW"},
  { value: "KRW", label: "KRW"},
  { value: "KWD", label: "KWD"},
  { value: "KYD", label: "KYD"},
  { value: "KZT", label: "KZT"},
  { value: "LAK", label: "LAK"},
  { value: "LBP", label: "LBP"},
  { value: "LKR", label: "LKR"},
  { value: "LRD", label: "LRD"},
  { value: "LSL", label: "LSL"},
  { value: "LYD", label: "LYD"},
  { value: "MAD", label: "MAD"},
  { value: "MDL", label: "MDL"},
  { value: "MGA", label: "MGA"},
  { value: "MKD", label: "MKD"},
  { value: "MMK", label: "MMK"},
  { value: "MNT", label: "MNT"},
  { value: "MOP", label: "MOP"},
  { value: "MRO", label: "MRO"},
  { value: "MRU", label: "MRU"},
  { value: "MUR", label: "MUR"},
  { value: "MVR", label: "MVR"},
  { value: "MWK", label: "MWK"},
  { value: "MXN", label: "MXN"},
  { value: "MYR", label: "MYR"},
  { value: "MZN", label: "MZN"},
  { value: "NAD", label: "NAD"},
  { value: "NGN", label: "NGN"},
  { value: "NIO", label: "NIO"},
  { value: "NOK", label: "NOK"},
  { value: "NPR", label: "NPR"},
  { value: "NZD", label: "NZD"},
  { value: "OMR", label: "OMR"},
  { value: "PAB", label: "PAB"},
  { value: "PEN", label: "PEN"},
  { value: "PGK", label: "PGK"},
  { value: "PHP", label: "PHP"},
  { value: "PKR", label: "PKR"},
  { value: "PLN", label: "PLN"},
  { value: "PYG", label: "PYG"},
  { value: "QAR", label: "QAR"},
  { value: "RON", label: "RON"},
  { value: "RSD", label: "RSD"},
  { value: "RUB", label: "RUB"},
  { value: "RWF", label: "RWF"},
  { value: "SAR", label: "SAR"},
  { value: "SBD", label: "SBD"},
  { value: "SCR", label: "SCR"},
  { value: "SDG", label: "SDG"},
  { value: "SEK", label: "SEK"},
  { value: "SGD", label: "SGD"},
  { value: "SHP", label: "SHP"},
  { value: "SLL", label: "SLL"},
  { value: "SOS", label: "SOS"},
  { value: "SRD", label: "SRD"},
  { value: "SSP", label: "SSP"},
  { value: "STD", label: "STD"},
  { value: "STN", label: "STN"},
  { value: "SVC", label: "SVC"},
  { value: "SYP", label: "SYP"},
  { value: "SZL", label: "SZL"},
  { value: "THB", label: "THB"},
  { value: "TJS", label: "TJS"},
  { value: "TMT", label: "TMT"},
  { value: "TND", label: "TND"},
  { value: "TOP", label: "TOP"},
  { value: "TRY", label: "TRY"},
  { value: "TTD", label: "TTD"},
  { value: "TWD", label: "TWD"},
  { value: "TZS", label: "TZS"},
  { value: "UAH", label: "UAH"},
  { value: "UGX", label: "UGX"},
  { value: "USD", label: "USD"},
  { value: "UYU", label: "UYU"},
  { value: "UZS", label: "UZS"},
  { value: "VEF", label: "VEF"},
  { value: "VES", label: "VES"},
  { value: "VND", label: "VND"},
  { value: "VUV", label: "VUV"},
  { value: "WST", label: "WST"},
  { value: "XAF", label: "XAF"},
  { value: "XAG", label: "XAG"},
  { value: "XAU", label: "XAU"},
  { value: "XCD", label: "XCD"},
  { value: "XDR", label: "XDR"},
  { value: "XOF", label: "XOF"},
  { value: "XPD", label: "XPD"},
  { value: "XPF", label: "XPF"},
  { value: "XPT", label: "XPT"},
  { value: "YER", label: "YER"},
  { value: "ZAR", label: "ZAR"},
  { value: "ZMW", label: "ZMW"},
  { value: "ZWL", label: "ZWL"},
]

export const currencies = [
  { value: "AED", label: "United Arab Emirates Dirham" },
  { value: "AFN", label: "Afghan Afghani" },
  { value: "ALL", label: "Albanian Lek" },
  { value: "AMD", label: "Armenian Dram" },
  { value: "ANG", label: "Netherlands Antillean Guilder" },
  { value: "AOA", label: "Angolan Kwanza" },
  { value: "ARS", label: "Argentine Peso" },
  { value: "AUD", label: "Australian Dollar" },
  { value: "AWG", label: "Aruban Florin" },
  { value: "AZN", label: "Azerbaijani Manat" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
  { value: "BBD", label: "Barbadian Dollar" },
  { value: "BDT", label: "Bangladeshi Taka" },
  { value: "BGN", label: "Bulgarian Lev" },
  { value: "BHD", label: "Bahraini Dinar" },
  { value: "BIF", label: "Burundian Franc" },
  { value: "BMD", label: "Bermudan Dollar" },
  { value: "BND", label: "Brunei Dollar" },
  { value: "BOB", label: "Bolivian Boliviano" },
  { value: "BRL", label: "Brazilian Real" },
  { value: "BSD", label: "Bahamian Dollar" },
  { value: "BTC", label: "Bitcoin" },
  { value: "BTN", label: "Bhutanese Ngultrum" },
  { value: "BWP", label: "Botswanan Pula" },
  { value: "BYN", label: "New Belarusian Ruble" },
  { value: "BYR", label: "Belarusian Ruble" },
  { value: "BZD", label: "Belize Dollar" },
  { value: "CAD", label: "Canadian Dollar" },
  { value: "CDF", label: "Congolese Franc" },
  { value: "CHF", label: "Swiss Franc" },
  { value: "CLF", label: "Chilean Unit of Account (UF)" },
  { value: "CLP", label: "Chilean Peso" },
  { value: "CNY", label: "Chinese Yuan" },
  { value: "COP", label: "Colombian Peso" },
  { value: "CRC", label: "Costa Rican Colón" },
  { value: "CUC", label: "Cuban Convertible Peso" },
  { value: "CUP", label: "Cuban Peso" },
  { value: "CVE", label: "Cape Verdean Escudo" },
  { value: "CZK", label: "Czech Republic Koruna" },
  { value: "DJF", label: "Djiboutian Franc" },
  { value: "DKK", label: "Danish Krone" },
  { value: "DOP", label: "Dominican Peso" },
  { value: "DZD", label: "Algerian Dinar" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "ERN", label: "Eritrean Nakfa" },
  { value: "ETB", label: "Ethiopian Birr" },
  { value: "EUR", label: "Euro" },
  { value: "FJD", label: "Fijian Dollar" },
  { value: "FKP", label: "Falkland Islands Pound" },
  { value: "GBP", label: "British Pound Sterling" },
  { value: "GEL", label: "Georgian Lari" },
  { value: "GGP", label: "Guernsey Pound" },
  { value: "GHS", label: "Ghanaian Cedi" },
  { value: "GIP", label: "Gibraltar Pound" },
  { value: "GMD", label: "Gambian Dalasi" },
  { value: "GNF", label: "Guinean Franc" },
  { value: "GTQ", label: "Guatemalan Quetzal" },
  { value: "GYD", label: "Guyanaese Dollar" },
  { value: "HKD", label: "Hong Kong Dollar" },
  { value: "HNL", label: "Honduran Lempira" },
  { value: "HRK", label: "Croatian Kuna" },
  { value: "HTG", label: "Haitian Gourde" },
  { value: "HUF", label: "Hungarian Forint" },
  { value: "IDR", label: "Indonesian Rupiah" },
  { value: "ILS", label: "Israeli New Sheqel" },
  { value: "IMP", label: "Manx pound" },
  { value: "INR", label: "Indian Rupee" },
  { value: "IQD", label: "Iraqi Dinar" },
  { value: "IRR", label: "Iranian Rial" },
  { value: "ISK", label: "Icelandic Króna" },
  { value: "JEP", label: "Jersey Pound" },
  { value: "JMD", label: "Jamaican Dollar" },
  { value: "JOD", label: "Jordanian Dinar" },
  { value: "JPY", label: "Japanese Yen" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "KGS", label: "Kyrgystani Som" },
  { value: "KHR", label: "Cambodian Riel" },
  { value: "KMF", label: "Comorian Franc" },
  { value: "KPW", label: "North Korean Won" },
  { value: "KRW", label: "South Korean Won" },
  { value: "KWD", label: "Kuwaiti Dinar" },
  { value: "KYD", label: "Cayman Islands Dollar" },
  { value: "KZT", label: "Kazakhstani Tenge" },
  { value: "LAK", label: "Laotian Kip" },
  { value: "LBP", label: "Lebanese Pound" },
  { value: "LKR", label: "Sri Lankan Rupee" },
  { value: "LRD", label: "Liberian Dollar" },
  { value: "LSL", label: "Lesotho Loti" },
  { value: "LTL", label: "Lithuanian Litas" },
  { value: "LVL", label: "Latvian Lats" },
  { value: "LYD", label: "Libyan Dinar" },
  { value: "MAD", label: "Moroccan Dirham" },
  { value: "MDL", label: "Moldovan Leu" },
  { value: "MGA", label: "Malagasy Ariary" },
  { value: "MKD", label: "Macedonian Denar" },
  { value: "MMK", label: "Myanma Kyat" },
  { value: "MNT", label: "Mongolian Tugrik" },
  { value: "MOP", label: "Macanese Pataca" },
  { value: "MRO", label: "Mauritanian Ouguiya" },
  { value: "MUR", label: "Mauritian Rupee" },
  { value: "MVR", label: "Maldivian Rufiyaa" },
  { value: "MWK", label: "Malawian Kwacha" },
  { value: "MXN", label: "Mexican Peso" },
  { value: "MYR", label: "Malaysian Ringgit" },
  { value: "MZN", label: "Mozambican Metical" },
  { value: "NAD", label: "Namibian Dollar" },
  { value: "NGN", label: "Nigerian Naira" },
  { value: "NIO", label: "Nicaraguan Córdoba" },
  { value: "NOK", label: "Norwegian Krone" },
  { value: "NPR", label: "Nepalese Rupee" },
  { value: "NZD", label: "New Zealand Dollar" },
  { value: "OMR", label: "Omani Rial" },
  { value: "PAB", label: "Panamanian Balboa" },
  { value: "PEN", label: "Peruvian Nuevo Sol" },
  { value: "PGK", label: "Papua New Guinean Kina" },
  { value: "PHP", label: "Philippine Peso" },
  { value: "PKR", label: "Pakistani Rupee" },
  { value: "PLN", label: "Polish Zloty" },
  { value: "PYG", label: "Paraguayan Guarani" },
  { value: "QAR", label: "Qatari Rial" },
  { value: "RON", label: "Romanian Leu" },
  { value: "RSD", label: "Serbian Dinar" },
  { value: "RUB", label: "Russian Ruble" },
  { value: "RWF", label: "Rwandan Franc" },
  { value: "SAR", label: "Saudi Riyal" },
  { value: "SBD", label: "Solomon Islands Dollar" },
  { value: "SCR", label: "Seychellois Rupee" },
  { value: "SDG", label: "Sudanese Pound" },
  { value: "SEK", label: "Swedish Krona" },
  { value: "SGD", label: "Singapore Dollar" },
  { value: "SHP", label: "Saint Helena Pound" },
  { value: "SLL", label: "Sierra Leonean Leone" },
  { value: "SOS", label: "Somali Shilling" },
  { value: "SRD", label: "Surinamese Dollar" },
  { value: "STD", label: "São Tomé and Príncipe Dobra" },
  { value: "SVC", label: "Salvadoran Colón" },
  { value: "SYP", label: "Syrian Pound" },
  { value: "SZL", label: "Swazi Lilangeni" },
  { value: "THB", label: "Thai Baht" },
  { value: "TJS", label: "Tajikistani Somoni" },
  { value: "TMT", label: "Turkmenistani Manat" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "TOP", label: "Tongan Paʻanga" },
  { value: "TRY", label: "Turkish Lira" },
  { value: "TTD", label: "Trinidad and Tobago Dollar" },
  { value: "TWD", label: "New Taiwan Dollar" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "UAH", label: "Ukrainian Hryvnia" },
  { value: "UGX", label: "Ugandan Shilling" },
  { value: "USD", label: "United States Dollar" },
  { value: "UYU", label: "Uruguayan Peso" },
  { value: "UZS", label: "Uzbekistan Som" },
  { value: "VEF", label: "Venezuelan Bolívar Fuerte" },
  { value: "VND", label: "Vietnamese Dong" },
  { value: "VUV", label: "Vanuatu Vatu" },
  { value: "WST", label: "Samoan Tala" },
  { value: "XAF", label: "CFA Franc BEAC" },
  { value: "XAG", label: "Silver (troy ounce)" },
  { value: "XAU", label: "Gold (troy ounce)" },
  { value: "XCD", label: "East Caribbean Dollar" },
  { value: "XDR", label: "Special Drawing Rights" },
  { value: "XOF", label: "CFA Franc BCEAO" },
  { value: "XPF", label: "CFP Franc" },
  { value: "YER", label: "Yemeni Rial" },
  { value: "ZAR", label: "South African Rand" },
  { value: "ZMK", label: "Zambian Kwacha (pre-2013)" },
  { value: "ZMW", label: "Zambian Kwacha" },
  { value: "ZWL", label: "Zimbabwean Dollar" },
]

export const countries = {
  "AED": "AE" ,
  "AFN": "AF" ,
  "ALL": "AL" ,
  "AMD": "AM" ,
  "ANG": "AN" ,
  "AOA": "AO" ,
  "ARS": "AR" ,
  "AUD": "AU" ,
  "AWG": "AW" ,
  "AZN": "AZ" ,
  "BAM": "BA" ,
  "BBD": "BB" ,
  "BDT": "BD" ,
  "BGN": "BG" ,
  "BHD": "BH" ,
  "BIF": "BI" ,
  "BMD": "BM" ,
  "BND": "BN" ,
  "BOB": "BO" ,
  "BRL": "BR" ,
  "BSD": "BS" ,
  "BTN": "BT" ,
  "BWP": "BW" ,
  "BYR": "BY" ,
  "BZD": "BZ" ,
  "CAD": "CA" ,
  "CDF": "CD" ,
  "CHF": "CH" ,
  "CLP": "CL" ,
  "CNY": "CN" ,
  "COP": "CO" ,
  "CRC": "CR" ,
  "CUP": "CU" ,
  "CVE": "CV" ,
  "CZK": "CZ" ,
  "DJF": "DJ" ,
  "DKK": "DK" ,
  "DOP": "DO" ,
  "DZD": "DZ" ,
  "EGP": "EG" ,
  "ERN": "ER" ,
  "ETB": "ET" ,
  "EUR": "EU" ,
  "FJD": "FJ" ,
  "FKP": "FK" ,
  "GBP": "GB" ,
  "GEL": "GE" ,
  "GHS": "GH" ,
  "GIP": "GI" ,
  "GMD": "GM" ,
  "GNF": "GN" ,
  "GTQ": "GT" ,
  "GYD": "GY" ,
  "HKD": "HK" ,
  "HNL": "HN" ,
  "HRK": "HR" ,
  "HTG": "HT" ,
  "HUF": "HU" ,
  "IDR": "ID" ,
  "ILS": "PS" ,
  "INR": "IN" ,
  "IQD": "IQ" ,
  "IRR": "IR" ,
  "ISK": "IS" ,
  "JMD": "JM" ,
  "JOD": "JO" ,
  "JPY": "JP" ,
  "KES": "KE" ,
  "KGS": "KG" ,
  "KHR": "KH" ,
  "KMF": "KM" ,
  "KPW": "KP" ,
  "KRW": "KR" ,
  "KWD": "KW" ,
  "KYD": "KY" ,
  "KZT": "KZ" ,
  "LAK": "LA" ,
  "LBP": "LB" ,
  "LKR": "LK" ,
  "LRD": "LR" ,
  "LSL": "LS" ,
  "LTL": "LT" ,
  "LYD": "LY" ,
  "MAD": "MA" ,
  "MDL": "MD" ,
  "MGA": "MG" ,
  "MKD": "MK" ,
  "MMK": "MM" ,
  "MNT": "MN" ,
  "MOP": "MO" ,
  "MRO": "MR" ,
  "MUR": "MU" ,
  "MVR": "MV" ,
  "MWK": "MW" ,
  "MXN": "MX" ,
  "MYR": "MY" ,
  "MZN": "MZ" ,
  "NAD": "NA" ,
  "NGN": "NG" ,
  "NIO": "NI" ,
  "NOK": "NO" ,
  "NPR": "NP" ,
  "NZD": "NZ" ,
  "OMR": "OM" ,
  "PAB": "PA" ,
  "PEN": "PE" ,
  "PGK": "PG" ,
  "PHP": "PH" ,
  "PKR": "PK" ,
  "PLN": "PL" ,
  "PYG": "PY" ,
  "QAR": "QA" ,
  "RON": "RO" ,
  "RSD": "RS" ,
  "RUB": "RU" ,
  "RWF": "RW" ,
  "SAR": "SA" ,
  "SBD": "SB" ,
  "SCR": "SC" ,
  "SDG": "SD" ,
  "SEK": "SE" ,
  "SGD": "SG" ,
  "SHP": "SH" ,
  "SLL": "SL" ,
  "SOS": "SO" ,
  "SRD": "SR" ,
  "SSP": "SS" ,
  "STD": "ST" ,
  "SYP": "SY" ,
  "SZL": "SZ" ,
  "THB": "TH" ,
  "TJS": "TJ" ,
  "TMT": "TM" ,
  "TND": "TN" ,
  "TOP": "TO" ,
  "TRY": "TR" ,
  "TTD": "TT" ,
  "TWD": "TW" ,
  "TZS": "TZ" ,
  "UAH": "UA" ,
  "UGX": "UG" ,
  "USD": "US" ,
  "UYU": "UY" ,
  "UZS": "UZ" ,
  "VEF": "VE" ,
  "VND": "VN" ,
  "VUV": "VU" ,
  "WST": "WS" ,
  "XAF": "CF" ,
  "XOF": "BF" ,
  "XPF": "PF" ,
  "YER": "YE" ,
  "ZAR": "ZA" ,
  "ZMK": "ZM" ,
  "ZWL": "ZW" ,
}