export const options = [
  { value: "AED", label: "AED"}, 
  { value: "AFN", label: "AFN"},
  { value: "ALL", label: "ALL"},
  { value: "AMD", label: "AMD"},
  { value: "ANG", label: "ANG"},
  { value: "AOA", label: "AOA"},
  { value: "ARS", label: "ARS"},
  { value: "AUD", label: "AUD"},
  { value: "AWG", label: "AWG"},
  { value: "AZN", label: "AZN"},
  { value: "BAM", label: "BAM"},
  { value: "BBD", label: "BBD"},
  { value: "BDT", label: "BDT"},
  { value: "BGN", label: "BGN"},
  { value: "BHD", label: "BHD"},
  { value: "BIF", label: "BIF"},
  { value: "BMD", label: "BMD"},
  { value: "BND", label: "BND"},
  { value: "BOB", label: "BOB"},
  { value: "BRL", label: "BRL"},
  { value: "BSD", label: "BSD"},
  { value: "BTC", label: "BTC"},
  { value: "BTN", label: "BTN"},
  { value: "BWP", label: "BWP"},
  { value: "BYN", label: "BYN"},
  { value: "BZD", label: "BZD"},
  { value: "CAD", label: "CAD"},
  { value: "CDF", label: "CDF"},
  { value: "CHF", label: "CHF"},
  { value: "CLF", label: "CLF"},
  { value: "CLP", label: "CLP"},
  { value: "CNH", label: "CNH"},
  { value: "CNY", label: "CNY"},
  { value: "COP", label: "COP"},
  { value: "CRC", label: "CRC"},
  { value: "CUC", label: "CUC"},
  { value: "CUP", label: "CUP"},
  { value: "CVE", label: "CVE"},
  { value: "CZK", label: "CZK"},
  { value: "DJF", label: "DJF"},
  { value: "DKK", label: "DKK"},
  { value: "DOP", label: "DOP"},
  { value: "DZD", label: "DZD"},
  { value: "EGP", label: "EGP"},
  { value: "ERN", label: "ERN"},
  { value: "ETB", label: "ETB"},
  { value: "EUR", label: "EUR"},
  { value: "FJD", label: "FJD"},
  { value: "FKP", label: "FKP"},
  { value: "GBP", label: "GBP"},
  { value: "GEL", label: "GEL"},
  { value: "GGP", label: "GGP"},
  { value: "GHS", label: "GHS"},
  { value: "GIP", label: "GIP"},
  { value: "GMD", label: "GMD"},
  { value: "GNF", label: "GNF"},
  { value: "GTQ", label: "GTQ"},
  { value: "GYD", label: "GYD"},
  { value: "HKD", label: "HKD"},
  { value: "HNL", label: "HNL"},
  { value: "HRK", label: "HRK"},
  { value: "HTG", label: "HTG"},
  { value: "HUF", label: "HUF"},
  { value: "IDR", label: "IDR"},
  { value: "ILS", label: "ILS"},
  { value: "IMP", label: "IMP"},
  { value: "INR", label: "INR"},
  { value: "IQD", label: "IQD"},
  { value: "IRR", label: "IRR"},
  { value: "ISK", label: "ISK"},
  { value: "JEP", label: "JEP"},
  { value: "JMD", label: "JMD"},
  { value: "JOD", label: "JOD"},
  { value: "JPY", label: "JPY"},
  { value: "KES", label: "KES"},
  { value: "KGS", label: "KGS"},
  { value: "KHR", label: "KHR"},
  { value: "KMF", label: "KMF"},
  { value: "KPW", label: "KPW"},
  { value: "KRW", label: "KRW"},
  { value: "KWD", label: "KWD"},
  { value: "KYD", label: "KYD"},
  { value: "KZT", label: "KZT"},
  { value: "LAK", label: "LAK"},
  { value: "LBP", label: "LBP"},
  { value: "LKR", label: "LKR"},
  { value: "LRD", label: "LRD"},
  { value: "LSL", label: "LSL"},
  { value: "LYD", label: "LYD"},
  { value: "MAD", label: "MAD"},
  { value: "MDL", label: "MDL"},
  { value: "MGA", label: "MGA"},
  { value: "MKD", label: "MKD"},
  { value: "MMK", label: "MMK"},
  { value: "MNT", label: "MNT"},
  { value: "MOP", label: "MOP"},
  { value: "MRO", label: "MRO"},
  { value: "MRU", label: "MRU"},
  { value: "MUR", label: "MUR"},
  { value: "MVR", label: "MVR"},
  { value: "MWK", label: "MWK"},
  { value: "MXN", label: "MXN"},
  { value: "MYR", label: "MYR"},
  { value: "MZN", label: "MZN"},
  { value: "NAD", label: "NAD"},
  { value: "NGN", label: "NGN"},
  { value: "NIO", label: "NIO"},
  { value: "NOK", label: "NOK"},
  { value: "NPR", label: "NPR"},
  { value: "NZD", label: "NZD"},
  { value: "OMR", label: "OMR"},
  { value: "PAB", label: "PAB"},
  { value: "PEN", label: "PEN"},
  { value: "PGK", label: "PGK"},
  { value: "PHP", label: "PHP"},
  { value: "PKR", label: "PKR"},
  { value: "PLN", label: "PLN"},
  { value: "PYG", label: "PYG"},
  { value: "QAR", label: "QAR"},
  { value: "RON", label: "RON"},
  { value: "RSD", label: "RSD"},
  { value: "RUB", label: "RUB"},
  { value: "RWF", label: "RWF"},
  { value: "SAR", label: "SAR"},
  { value: "SBD", label: "SBD"},
  { value: "SCR", label: "SCR"},
  { value: "SDG", label: "SDG"},
  { value: "SEK", label: "SEK"},
  { value: "SGD", label: "SGD"},
  { value: "SHP", label: "SHP"},
  { value: "SLL", label: "SLL"},
  { value: "SOS", label: "SOS"},
  { value: "SRD", label: "SRD"},
  { value: "SSP", label: "SSP"},
  { value: "STD", label: "STD"},
  { value: "STN", label: "STN"},
  { value: "SVC", label: "SVC"},
  { value: "SYP", label: "SYP"},
  { value: "SZL", label: "SZL"},
  { value: "THB", label: "THB"},
  { value: "TJS", label: "TJS"},
  { value: "TMT", label: "TMT"},
  { value: "TND", label: "TND"},
  { value: "TOP", label: "TOP"},
  { value: "TRY", label: "TRY"},
  { value: "TTD", label: "TTD"},
  { value: "TWD", label: "TWD"},
  { value: "TZS", label: "TZS"},
  { value: "UAH", label: "UAH"},
  { value: "UGX", label: "UGX"},
  { value: "USD", label: "USD"},
  { value: "UYU", label: "UYU"},
  { value: "UZS", label: "UZS"},
  { value: "VEF", label: "VEF"},
  { value: "VES", label: "VES"},
  { value: "VND", label: "VND"},
  { value: "VUV", label: "VUV"},
  { value: "WST", label: "WST"},
  { value: "XAF", label: "XAF"},
  { value: "XAG", label: "XAG"},
  { value: "XAU", label: "XAU"},
  { value: "XCD", label: "XCD"},
  { value: "XDR", label: "XDR"},
  { value: "XOF", label: "XOF"},
  { value: "XPD", label: "XPD"},
  { value: "XPF", label: "XPF"},
  { value: "XPT", label: "XPT"},
  { value: "YER", label: "YER"},
  { value: "ZAR", label: "ZAR"},
  { value: "ZMW", label: "ZMW"},
  { value: "ZWL", label: "ZWL"},
]

export const currencies = {
  "AED": "United Arab Emirates Dirham",
  "AFN": "Afghan Afghani",
  "ALL": "Albanian Lek",
  "AMD": "Armenian Dram",
  "ANG": "Netherlands Antillean Guilder",
  "AOA": "Angolan Kwanza",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AWG": "Aruban Florin",
  "AZN": "Azerbaijani Manat",
  "BAM": "Bosnia-Herzegovina Convertible Mark",
  "BBD": "Barbadian Dollar",
  "BDT": "Bangladeshi Taka",
  "BGN": "Bulgarian Lev",
  "BHD": "Bahraini Dinar",
  "BIF": "Burundian Franc",
  "BMD": "Bermudan Dollar",
  "BND": "Brunei Dollar",
  "BOB": "Bolivian Boliviano",
  "BRL": "Brazilian Real",
  "BSD": "Bahamian Dollar",
  "BTC": "Bitcoin",
  "BTN": "Bhutanese Ngultrum",
  "BWP": "Botswanan Pula",
  "BYN": "New Belarusian Ruble",
  "BYR": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "CAD": "Canadian Dollar",
  "CDF": "Congolese Franc",
  "CHF": "Swiss Franc",
  "CLF": "Chilean Unit of Account (UF)",
  "CLP": "Chilean Peso",
  "CNY": "Chinese Yuan",
  "COP": "Colombian Peso",
  "CRC": "Costa Rican Colón",
  "CUC": "Cuban Convertible Peso",
  "CUP": "Cuban Peso",
  "CVE": "Cape Verdean Escudo",
  "CZK": "Czech Republic Koruna",
  "DJF": "Djiboutian Franc",
  "DKK": "Danish Krone",
  "DOP": "Dominican Peso",
  "DZD": "Algerian Dinar",
  "EGP": "Egyptian Pound",
  "ERN": "Eritrean Nakfa",
  "ETB": "Ethiopian Birr",
  "EUR": "Euro",
  "FJD": "Fijian Dollar",
  "FKP": "Falkland Islands Pound",
  "GBP": "British Pound Sterling",
  "GEL": "Georgian Lari",
  "GGP": "Guernsey Pound",
  "GHS": "Ghanaian Cedi",
  "GIP": "Gibraltar Pound",
  "GMD": "Gambian Dalasi",
  "GNF": "Guinean Franc",
  "GTQ": "Guatemalan Quetzal",
  "GYD": "Guyanaese Dollar",
  "HKD": "Hong Kong Dollar",
  "HNL": "Honduran Lempira",
  "HRK": "Croatian Kuna",
  "HTG": "Haitian Gourde",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli New Sheqel",
  "IMP": "Manx pound",
  "INR": "Indian Rupee",
  "IQD": "Iraqi Dinar",
  "IRR": "Iranian Rial",
  "ISK": "Icelandic Króna",
  "JEP": "Jersey Pound",
  "JMD": "Jamaican Dollar",
  "JOD": "Jordanian Dinar",
  "JPY": "Japanese Yen",
  "KES": "Kenyan Shilling",
  "KGS": "Kyrgystani Som",
  "KHR": "Cambodian Riel",
  "KMF": "Comorian Franc",
  "KPW": "North Korean Won",
  "KRW": "South Korean Won",
  "KWD": "Kuwaiti Dinar",
  "KYD": "Cayman Islands Dollar",
  "KZT": "Kazakhstani Tenge",
  "LAK": "Laotian Kip",
  "LBP": "Lebanese Pound",
  "LKR": "Sri Lankan Rupee",
  "LRD": "Liberian Dollar",
  "LSL": "Lesotho Loti",
  "LTL": "Lithuanian Litas",
  "LVL": "Latvian Lats",
  "LYD": "Libyan Dinar",
  "MAD": "Moroccan Dirham",
  "MDL": "Moldovan Leu",
  "MGA": "Malagasy Ariary",
  "MKD": "Macedonian Denar",
  "MMK": "Myanma Kyat",
  "MNT": "Mongolian Tugrik",
  "MOP": "Macanese Pataca",
  "MRO": "Mauritanian Ouguiya",
  "MUR": "Mauritian Rupee",
  "MVR": "Maldivian Rufiyaa",
  "MWK": "Malawian Kwacha",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "MZN": "Mozambican Metical",
  "NAD": "Namibian Dollar",
  "NGN": "Nigerian Naira",
  "NIO": "Nicaraguan Córdoba",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "OMR": "Omani Rial",
  "PAB": "Panamanian Balboa",
  "PEN": "Peruvian Nuevo Sol",
  "PGK": "Papua New Guinean Kina",
  "PHP": "Philippine Peso",
  "PKR": "Pakistani Rupee",
  "PLN": "Polish Zloty",
  "PYG": "Paraguayan Guarani",
  "QAR": "Qatari Rial",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "RUB": "Russian Ruble",
  "RWF": "Rwandan Franc",
  "SAR": "Saudi Riyal",
  "SBD": "Solomon Islands Dollar",
  "SCR": "Seychellois Rupee",
  "SDG": "Sudanese Pound",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "SHP": "Saint Helena Pound",
  "SLL": "Sierra Leonean Leone",
  "SOS": "Somali Shilling",
  "SRD": "Surinamese Dollar",
  "STD": "São Tomé and Príncipe Dobra",
  "SVC": "Salvadoran Colón",
  "SYP": "Syrian Pound",
  "SZL": "Swazi Lilangeni",
  "THB": "Thai Baht",
  "TJS": "Tajikistani Somoni",
  "TMT": "Turkmenistani Manat",
  "TND": "Tunisian Dinar",
  "TOP": "Tongan Paʻanga",
  "TRY": "Turkish Lira",
  "TTD": "Trinidad and Tobago Dollar",
  "TWD": "New Taiwan Dollar",
  "TZS": "Tanzanian Shilling",
  "UAH": "Ukrainian Hryvnia",
  "UGX": "Ugandan Shilling",
  "USD": "United States Dollar",
  "UYU": "Uruguayan Peso",
  "UZS": "Uzbekistan Som",
  "VEF": "Venezuelan Bolívar Fuerte",
  "VND": "Vietnamese Dong",
  "VUV": "Vanuatu Vatu",
  "WST": "Samoan Tala",
  "XAF": "CFA Franc BEAC",
  "XAG": "Silver (troy ounce)",
  "XAU": "Gold (troy ounce)",
  "XCD": "East Caribbean Dollar",
  "XDR": "Special Drawing Rights",
  "XOF": "CFA Franc BCEAO",
  "XPF": "CFP Franc",
  "YER": "Yemeni Rial",
  "ZAR": "South African Rand",
  "ZMK": "Zambian Kwacha (pre-2013)",
  "ZMW": "Zambian Kwacha",
  "ZWL": "Zimbabwean Dollar",
}

export const countries = {
  "AED": "AE" ,
  "AFN": "AF" ,
  "ALL": "AL" ,
  "AMD": "AM" ,
  "ANG": "AN" ,
  "AOA": "AO" ,
  "ARS": "AR" ,
  "AUD": "AU" ,
  "AWG": "AW" ,
  "AZN": "AZ" ,
  "BAM": "BA" ,
  "BBD": "BB" ,
  "BDT": "BD" ,
  "BGN": "BG" ,
  "BHD": "BH" ,
  "BIF": "BI" ,
  "BMD": "BM" ,
  "BND": "BN" ,
  "BOB": "BO" ,
  "BRL": "BR" ,
  "BSD": "BS" ,
  "BTN": "BT" ,
  "BWP": "BW" ,
  "BYR": "BY" ,
  "BZD": "BZ" ,
  "CAD": "CA" ,
  "CDF": "CD" ,
  "CHF": "CH" ,
  "CLP": "CL" ,
  "CNY": "CN" ,
  "COP": "CO" ,
  "CRC": "CR" ,
  "CUP": "CU" ,
  "CVE": "CV" ,
  "CZK": "CZ" ,
  "DJF": "DJ" ,
  "DKK": "DK" ,
  "DOP": "DO" ,
  "DZD": "DZ" ,
  "EGP": "EG" ,
  "ERN": "ER" ,
  "ETB": "ET" ,
  "EUR": "EU" ,
  "FJD": "FJ" ,
  "FKP": "FK" ,
  "GBP": "GB" ,
  "GEL": "GE" ,
  "GHS": "GH" ,
  "GIP": "GI" ,
  "GMD": "GM" ,
  "GNF": "GN" ,
  "GTQ": "GT" ,
  "GYD": "GY" ,
  "HKD": "HK" ,
  "HNL": "HN" ,
  "HRK": "HR" ,
  "HTG": "HT" ,
  "HUF": "HU" ,
  "IDR": "ID" ,
  "ILS": "PS" ,
  "INR": "IN" ,
  "IQD": "IQ" ,
  "IRR": "IR" ,
  "ISK": "IS" ,
  "JMD": "JM" ,
  "JOD": "JO" ,
  "JPY": "JP" ,
  "KES": "KE" ,
  "KGS": "KG" ,
  "KHR": "KH" ,
  "KMF": "KM" ,
  "KPW": "KP" ,
  "KRW": "KR" ,
  "KWD": "KW" ,
  "KYD": "KY" ,
  "KZT": "KZ" ,
  "LAK": "LA" ,
  "LBP": "LB" ,
  "LKR": "LK" ,
  "LRD": "LR" ,
  "LSL": "LS" ,
  "LTL": "LT" ,
  "LYD": "LY" ,
  "MAD": "MA" ,
  "MDL": "MD" ,
  "MGA": "MG" ,
  "MKD": "MK" ,
  "MMK": "MM" ,
  "MNT": "MN" ,
  "MOP": "MO" ,
  "MRO": "MR" ,
  "MUR": "MU" ,
  "MVR": "MV" ,
  "MWK": "MW" ,
  "MXN": "MX" ,
  "MYR": "MY" ,
  "MZN": "MZ" ,
  "NAD": "NA" ,
  "NGN": "NG" ,
  "NIO": "NI" ,
  "NOK": "NO" ,
  "NPR": "NP" ,
  "NZD": "NZ" ,
  "OMR": "OM" ,
  "PAB": "PA" ,
  "PEN": "PE" ,
  "PGK": "PG" ,
  "PHP": "PH" ,
  "PKR": "PK" ,
  "PLN": "PL" ,
  "PYG": "PY" ,
  "QAR": "QA" ,
  "RON": "RO" ,
  "RSD": "RS" ,
  "RUB": "RU" ,
  "RWF": "RW" ,
  "SAR": "SA" ,
  "SBD": "SB" ,
  "SCR": "SC" ,
  "SDG": "SD" ,
  "SEK": "SE" ,
  "SGD": "SG" ,
  "SHP": "SH" ,
  "SLL": "SL" ,
  "SOS": "SO" ,
  "SRD": "SR" ,
  "SSP": "SS" ,
  "STD": "ST" ,
  "SYP": "SY" ,
  "SZL": "SZ" ,
  "THB": "TH" ,
  "TJS": "TJ" ,
  "TMT": "TM" ,
  "TND": "TN" ,
  "TOP": "TO" ,
  "TRY": "TR" ,
  "TTD": "TT" ,
  "TWD": "TW" ,
  "TZS": "TZ" ,
  "UAH": "UA" ,
  "UGX": "UG" ,
  "USD": "US" ,
  "UYU": "UY" ,
  "UZS": "UZ" ,
  "VEF": "VE" ,
  "VND": "VN" ,
  "VUV": "VU" ,
  "WST": "WS" ,
  "XAF": "CF" ,
  "XOF": "BF" ,
  "XPF": "PF" ,
  "YER": "YE" ,
  "ZAR": "ZA" ,
  "ZMK": "ZM" ,
  "ZWL": "ZW" ,
}