export const options = [
  { value: "AED", label: "AED"}, 
  { value: "AFN", label: "AFN"},
  { value: "ALL", label: "ALL"},
  { value: "AMD", label: "AMD"},
  { value: "ANG", label: "ANG"},
  { value: "AOA", label: "AOA"},
  { value: "ARS", label: "ARS"},
  { value: "AUD", label: "AUD"},
  { value: "AWG", label: "AWG"},
  { value: "AZN", label: "AZN"},
  { value: "BAM", label: "BAM"},
  { value: "BBD", label: "BBD"},
  { value: "BDT", label: "BDT"},
  { value: "BGN", label: "BGN"},
  { value: "BHD", label: "BHD"},
  { value: "BIF", label: "BIF"},
  { value: "BMD", label: "BMD"},
  { value: "BND", label: "BND"},
  { value: "BOB", label: "BOB"},
  { value: "BRL", label: "BRL"},
  { value: "BSD", label: "BSD"},
  { value: "BTC", label: "BTC"},
  { value: "BTN", label: "BTN"},
  { value: "BWP", label: "BWP"},
  { value: "BYN", label: "BYN"},
  { value: "BZD", label: "BZD"},
  { value: "CAD", label: "CAD"},
  { value: "CDF", label: "CDF"},
  { value: "CHF", label: "CHF"},
  { value: "CLF", label: "CLF"},
  { value: "CLP", label: "CLP"},
  { value: "CNH", label: "CNH"},
  { value: "CNY", label: "CNY"},
  { value: "COP", label: "COP"},
  { value: "CRC", label: "CRC"},
  { value: "CUC", label: "CUC"},
  { value: "CUP", label: "CUP"},
  { value: "CVE", label: "CVE"},
  { value: "CZK", label: "CZK"},
  { value: "DJF", label: "DJF"},
  { value: "DKK", label: "DKK"},
  { value: "DOP", label: "DOP"},
  { value: "DZD", label: "DZD"},
  { value: "EGP", label: "EGP"},
  { value: "ERN", label: "ERN"},
  { value: "ETB", label: "ETB"},
  { value: "EUR", label: "EUR"},
  { value: "FJD", label: "FJD"},
  { value: "FKP", label: "FKP"},
  { value: "GBP", label: "GBP"},
  { value: "GEL", label: "GEL"},
  { value: "GGP", label: "GGP"},
  { value: "GHS", label: "GHS"},
  { value: "GIP", label: "GIP"},
  { value: "GMD", label: "GMD"},
  { value: "GNF", label: "GNF"},
  { value: "GTQ", label: "GTQ"},
  { value: "GYD", label: "GYD"},
  { value: "HKD", label: "HKD"},
  { value: "HNL", label: "HNL"},
  { value: "HRK", label: "HRK"},
  { value: "HTG", label: "HTG"},
  { value: "HUF", label: "HUF"},
  { value: "IDR", label: "IDR"},
  { value: "ILS", label: "ILS"},
  { value: "IMP", label: "IMP"},
  { value: "INR", label: "INR"},
  { value: "IQD", label: "IQD"},
  { value: "IRR", label: "IRR"},
  { value: "ISK", label: "ISK"},
  { value: "JEP", label: "JEP"},
  { value: "JMD", label: "JMD"},
  { value: "JOD", label: "JOD"},
  { value: "JPY", label: "JPY"},
  { value: "KES", label: "KES"},
  { value: "KGS", label: "KGS"},
  { value: "KHR", label: "KHR"},
  { value: "KMF", label: "KMF"},
  { value: "KPW", label: "KPW"},
  { value: "KRW", label: "KRW"},
  { value: "KWD", label: "KWD"},
  { value: "KYD", label: "KYD"},
  { value: "KZT", label: "KZT"},
  { value: "LAK", label: "LAK"},
  { value: "LBP", label: "LBP"},
  { value: "LKR", label: "LKR"},
  { value: "LRD", label: "LRD"},
  { value: "LSL", label: "LSL"},
  { value: "LYD", label: "LYD"},
  { value: "MAD", label: "MAD"},
  { value: "MDL", label: "MDL"},
  { value: "MGA", label: "MGA"},
  { value: "MKD", label: "MKD"},
  { value: "MMK", label: "MMK"},
  { value: "MNT", label: "MNT"},
  { value: "MOP", label: "MOP"},
  { value: "MRO", label: "MRO"},
  { value: "MRU", label: "MRU"},
  { value: "MUR", label: "MUR"},
  { value: "MVR", label: "MVR"},
  { value: "MWK", label: "MWK"},
  { value: "MXN", label: "MXN"},
  { value: "MYR", label: "MYR"},
  { value: "MZN", label: "MZN"},
  { value: "NAD", label: "NAD"},
  { value: "NGN", label: "NGN"},
  { value: "NIO", label: "NIO"},
  { value: "NOK", label: "NOK"},
  { value: "NPR", label: "NPR"},
  { value: "NZD", label: "NZD"},
  { value: "OMR", label: "OMR"},
  { value: "PAB", label: "PAB"},
  { value: "PEN", label: "PEN"},
  { value: "PGK", label: "PGK"},
  { value: "PHP", label: "PHP"},
  { value: "PKR", label: "PKR"},
  { value: "PLN", label: "PLN"},
  { value: "PYG", label: "PYG"},
  { value: "QAR", label: "QAR"},
  { value: "RON", label: "RON"},
  { value: "RSD", label: "RSD"},
  { value: "RUB", label: "RUB"},
  { value: "RWF", label: "RWF"},
  { value: "SAR", label: "SAR"},
  { value: "SBD", label: "SBD"},
  { value: "SCR", label: "SCR"},
  { value: "SDG", label: "SDG"},
  { value: "SEK", label: "SEK"},
  { value: "SGD", label: "SGD"},
  { value: "SHP", label: "SHP"},
  { value: "SLL", label: "SLL"},
  { value: "SOS", label: "SOS"},
  { value: "SRD", label: "SRD"},
  { value: "SSP", label: "SSP"},
  { value: "STD", label: "STD"},
  { value: "STN", label: "STN"},
  { value: "SVC", label: "SVC"},
  { value: "SYP", label: "SYP"},
  { value: "SZL", label: "SZL"},
  { value: "THB", label: "THB"},
  { value: "TJS", label: "TJS"},
  { value: "TMT", label: "TMT"},
  { value: "TND", label: "TND"},
  { value: "TOP", label: "TOP"},
  { value: "TRY", label: "TRY"},
  { value: "TTD", label: "TTD"},
  { value: "TWD", label: "TWD"},
  { value: "TZS", label: "TZS"},
  { value: "UAH", label: "UAH"},
  { value: "UGX", label: "UGX"},
  { value: "USD", label: "USD"},
  { value: "UYU", label: "UYU"},
  { value: "UZS", label: "UZS"},
  { value: "VEF", label: "VEF"},
  { value: "VES", label: "VES"},
  { value: "VND", label: "VND"},
  { value: "VUV", label: "VUV"},
  { value: "WST", label: "WST"},
  { value: "XAF", label: "XAF"},
  { value: "XAG", label: "XAG"},
  { value: "XAU", label: "XAU"},
  { value: "XCD", label: "XCD"},
  { value: "XDR", label: "XDR"},
  { value: "XOF", label: "XOF"},
  { value: "XPD", label: "XPD"},
  { value: "XPF", label: "XPF"},
  { value: "XPT", label: "XPT"},
  { value: "YER", label: "YER"},
  { value: "ZAR", label: "ZAR"},
  { value: "ZMW", label: "ZMW"},
  { value: "ZWL", label: "ZWL"},
]

export const currencies = [
  { value: "AED", label: "United Arab Emirates Dirham" },
  { value: "AFN", label: "Afghan Afghani" },
  { value: "ALL", label: "Albanian Lek" },
  { value: "AMD", label: "Armenian Dram" },
  { value: "ANG", label: "Netherlands Antillean Guilder" },
  { value: "AOA", label: "Angolan Kwanza" },
  { value: "ARS", label: "Argentine Peso" },
  { value: "AUD", label: "Australian Dollar" },
  { value: "AWG", label: "Aruban Florin" },
  { value: "AZN", label: "Azerbaijani Manat" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
  { value: "BBD", label: "Barbadian Dollar" },
  { value: "BDT", label: "Bangladeshi Taka" },
  { value: "BGN", label: "Bulgarian Lev" },
  { value: "BHD", label: "Bahraini Dinar" },
  { value: "BIF", label: "Burundian Franc" },
  { value: "BMD", label: "Bermudan Dollar" },
  { value: "BND", label: "Brunei Dollar" },
  { value: "BOB", label: "Bolivian Boliviano" },
  { value: "BRL", label: "Brazilian Real" },
  { value: "BSD", label: "Bahamian Dollar" },
  { value: "BTC", label: "Bitcoin" },
  { value: "BTN", label: "Bhutanese Ngultrum" },
  { value: "BWP", label: "Botswanan Pula" },
  { value: "BYN", label: "New Belarusian Ruble" },
  { value: "BYR", label: "Belarusian Ruble" },
  { value: "BZD", label: "Belize Dollar" },
  { value: "CAD", label: "Canadian Dollar" },
  { value: "CDF", label: "Congolese Franc" },
  { value: "CHF", label: "Swiss Franc" },
  { value: "CLF", label: "Chilean Unit of Account (UF)" },
  { value: "CLP", label: "Chilean Peso" },
  { value: "CNY", label: "Chinese Yuan" },
  { value: "COP", label: "Colombian Peso" },
  { value: "CRC", label: "Costa Rican Colón" },
  { value: "CUC", label: "Cuban Convertible Peso" },
  { value: "CUP", label: "Cuban Peso" },
  { value: "CVE", label: "Cape Verdean Escudo" },
  { value: "CZK", label: "Czech Republic Koruna" },
  { value: "DJF", label: "Djiboutian Franc" },
  { value: "DKK", label: "Danish Krone" },
  { value: "DOP", label: "Dominican Peso" },
  { value: "DZD", label: "Algerian Dinar" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "ERN", label: "Eritrean Nakfa" },
  { value: "ETB", label: "Ethiopian Birr" },
  { value: "EUR", label: "Euro" },
  { value: "FJD", label: "Fijian Dollar" },
  { value: "FKP", label: "Falkland Islands Pound" },
  { value: "GBP", label: "British Pound Sterling" },
  { value: "GEL", label: "Georgian Lari" },
  { value: "GGP", label: "Guernsey Pound" },
  { value: "GHS", label: "Ghanaian Cedi" },
  { value: "GIP", label: "Gibraltar Pound" },
  { value: "GMD", label: "Gambian Dalasi" },
  { value: "GNF", label: "Guinean Franc" },
  { value: "GTQ", label: "Guatemalan Quetzal" },
  { value: "GYD", label: "Guyanaese Dollar" },
  { value: "HKD", label: "Hong Kong Dollar" },
  { value: "HNL", label: "Honduran Lempira" },
  { value: "HRK", label: "Croatian Kuna" },
  { value: "HTG", label: "Haitian Gourde" },
  { value: "HUF", label: "Hungarian Forint" },
  { value: "IDR", label: "Indonesian Rupiah" },
  { value: "ILS", label: "Israeli New Sheqel" },
  { value: "IMP", label: "Manx pound" },
  { value: "INR", label: "Indian Rupee" },
  { value: "IQD", label: "Iraqi Dinar" },
  { value: "IRR", label: "Iranian Rial" },
  { value: "ISK", label: "Icelandic Króna" },
  { value: "JEP", label: "Jersey Pound" },
  { value: "JMD", label: "Jamaican Dollar" },
  { value: "JOD", label: "Jordanian Dinar" },
  { value: "JPY", label: "Japanese Yen" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "KGS", label: "Kyrgystani Som" },
  { value: "KHR", label: "Cambodian Riel" },
  { value: "KMF", label: "Comorian Franc" },
  { value: "KPW", label: "North Korean Won" },
  { value: "KRW", label: "South Korean Won" },
  { value: "KWD", label: "Kuwaiti Dinar" },
  { value: "KYD", label: "Cayman Islands Dollar" },
  { value: "KZT", label: "Kazakhstani Tenge" },
  { value: "LAK", label: "Laotian Kip" },
  { value: "LBP", label: "Lebanese Pound" },
  { value: "LKR", label: "Sri Lankan Rupee" },
  { value: "LRD", label: "Liberian Dollar" },
  { value: "LSL", label: "Lesotho Loti" },
  { value: "LTL", label: "Lithuanian Litas" },
  { value: "LVL", label: "Latvian Lats" },
  { value: "LYD", label: "Libyan Dinar" },
  { value: "MAD", label: "Moroccan Dirham" },
  { value: "MDL", label: "Moldovan Leu" },
  { value: "MGA", label: "Malagasy Ariary" },
  { value: "MKD", label: "Macedonian Denar" },
  { value: "MMK", label: "Myanma Kyat" },
  { value: "MNT", label: "Mongolian Tugrik" },
  { value: "MOP", label: "Macanese Pataca" },
  { value: "MRO", label: "Mauritanian Ouguiya" },
  { value: "MUR", label: "Mauritian Rupee" },
  { value: "MVR", label: "Maldivian Rufiyaa" },
  { value: "MWK", label: "Malawian Kwacha" },
  { value: "MXN", label: "Mexican Peso" },
  { value: "MYR", label: "Malaysian Ringgit" },
  { value: "MZN", label: "Mozambican Metical" },
  { value: "NAD", label: "Namibian Dollar" },
  { value: "NGN", label: "Nigerian Naira" },
  { value: "NIO", label: "Nicaraguan Córdoba" },
  { value: "NOK", label: "Norwegian Krone" },
  { value: "NPR", label: "Nepalese Rupee" },
  { value: "NZD", label: "New Zealand Dollar" },
  { value: "OMR", label: "Omani Rial" },
  { value: "PAB", label: "Panamanian Balboa" },
  { value: "PEN", label: "Peruvian Nuevo Sol" },
  { value: "PGK", label: "Papua New Guinean Kina" },
  { value: "PHP", label: "Philippine Peso" },
  { value: "PKR", label: "Pakistani Rupee" },
  { value: "PLN", label: "Polish Zloty" },
  { value: "PYG", label: "Paraguayan Guarani" },
  { value: "QAR", label: "Qatari Rial" },
  { value: "RON", label: "Romanian Leu" },
  { value: "RSD", label: "Serbian Dinar" },
  { value: "RUB", label: "Russian Ruble" },
  { value: "RWF", label: "Rwandan Franc" },
  { value: "SAR", label: "Saudi Riyal" },
  { value: "SBD", label: "Solomon Islands Dollar" },
  { value: "SCR", label: "Seychellois Rupee" },
  { value: "SDG", label: "Sudanese Pound" },
  { value: "SEK", label: "Swedish Krona" },
  { value: "SGD", label: "Singapore Dollar" },
  { value: "SHP", label: "Saint Helena Pound" },
  { value: "SLL", label: "Sierra Leonean Leone" },
  { value: "SOS", label: "Somali Shilling" },
  { value: "SRD", label: "Surinamese Dollar" },
  { value: "STD", label: "São Tomé and Príncipe Dobra" },
  { value: "SVC", label: "Salvadoran Colón" },
  { value: "SYP", label: "Syrian Pound" },
  { value: "SZL", label: "Swazi Lilangeni" },
  { value: "THB", label: "Thai Baht" },
  { value: "TJS", label: "Tajikistani Somoni" },
  { value: "TMT", label: "Turkmenistani Manat" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "TOP", label: "Tongan Paʻanga" },
  { value: "TRY", label: "Turkish Lira" },
  { value: "TTD", label: "Trinidad and Tobago Dollar" },
  { value: "TWD", label: "New Taiwan Dollar" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "UAH", label: "Ukrainian Hryvnia" },
  { value: "UGX", label: "Ugandan Shilling" },
  { value: "USD", label: "United States Dollar" },
  { value: "UYU", label: "Uruguayan Peso" },
  { value: "UZS", label: "Uzbekistan Som" },
  { value: "VEF", label: "Venezuelan Bolívar Fuerte" },
  { value: "VND", label: "Vietnamese Dong" },
  { value: "VUV", label: "Vanuatu Vatu" },
  { value: "WST", label: "Samoan Tala" },
  { value: "XAF", label: "CFA Franc BEAC" },
  { value: "XAG", label: "Silver (troy ounce)" },
  { value: "XAU", label: "Gold (troy ounce)" },
  { value: "XCD", label: "East Caribbean Dollar" },
  { value: "XDR", label: "Special Drawing Rights" },
  { value: "XOF", label: "CFA Franc BCEAO" },
  { value: "XPF", label: "CFP Franc" },
  { value: "YER", label: "Yemeni Rial" },
  { value: "ZAR", label: "South African Rand" },
  { value: "ZMK", label: "Zambian Kwacha (pre-2013)" },
  { value: "ZMW", label: "Zambian Kwacha" },
  { value: "ZWL", label: "Zimbabwean Dollar" },
]

export const countries = [
  {value: "AED", label: "AE"} , 
  {value: "AFN", label: "AF"} , 
  {value: "ALL", label: "AL"} ,
  {value: "AMD", label: "AM"} ,
  {value: "ANG", label: "AN"} ,
  {value: "AOA", label: "AO"} ,
  {value: "ARS", label: "AR"} ,
  {value: "AUD", label: "AU"} ,
  {value: "AWG", label: "AW"} ,
  {value: "AZN", label: "AZ"} ,
  {value: "BAM", label: "BA"} ,
  {value: "BBD", label: "BB"} ,
  {value: "BDT", label: "BD"} ,
  {value: "BGN", label: "BG"} ,
  {value: "BHD", label: "BH"} ,
  {value: "BIF", label: "BI"} ,
  {value: "BMD", label: "BM"} ,
  {value: "BND", label: "BN"} ,
  {value: "BOB", label: "BO"} ,
  {value: "BRL", label: "BR"} ,
  {value: "BSD", label: "BS"} ,
  {value: "BTN", label: "BT"} ,
  {value: "BWP", label: "BW"} ,
  {value: "BYR", label: "BY"} ,
  {value: "BZD", label: "BZ"} ,
  {value: "CAD", label: "CA"} ,
  {value: "CDF", label: "CD"} ,
  {value: "CHF", label: "CH"} ,
  {value: "CLP", label: "CL"} ,
  {value: "CNY", label: "CN"} ,
  {value: "COP", label: "CO"} ,
  {value: "CRC", label: "CR"} ,
  {value: "CUC", label: "CU"} ,
  {value: "CUP", label: "CU"} ,
  {value: "CVE", label: "CV"} ,
  {value: "CZK", label: "CZ"} ,
  {value: "DJF", label: "DJ"} ,
  {value: "DKK", label: "DK"} ,
  {value: "DOP", label: "DO"} ,
  {value: "DZD", label: "DZ"} ,
  {value: "EGP", label: "EG"} ,
  {value: "ERN", label: "ER"} ,
  {value: "ETB", label: "ET"} ,
  {value: "EUR", label: "EU"} ,
  {value: "FJD", label: "FJ"} ,
  {value: "FKP", label: "FK"} ,
  {value: "GBP", label: "GB"} ,
  {value: "GEL", label: "GE"} ,
  {value: "GHS", label: "GH"} ,
  {value: "GIP", label: "GI"} ,
  {value: "GMD", label: "GM"} ,
  {value: "GNF", label: "GN"} ,
  {value: "GTQ", label: "GT"} ,
  {value: "GYD", label: "GY"} ,
  {value: "HKD", label: "HK"} ,
  {value: "HNL", label: "HN"} ,
  {value: "HRK", label: "HR"} ,
  {value: "HTG", label: "HT"} ,
  {value: "HUF", label: "HU"} ,
  {value: "IDR", label: "ID"} ,
  {value: "ILS", label: "PS"} ,
  {value: "INR", label: "IN"} ,
  {value: "IQD", label: "IQ"} ,
  {value: "IRR", label: "IR"} ,
  {value: "ISK", label: "IS"} ,
  {value: "JMD", label: "JM"} ,
  {value: "JOD", label: "JO"} ,
  {value: "JPY", label: "JP"} ,
  {value: "KES", label: "KE"} ,
  {value: "KGS", label: "KG"} ,
  {value: "KHR", label: "KH"} ,
  {value: "KMF", label: "KM"} ,
  {value: "KPW", label: "KP"} ,
  {value: "KRW", label: "KR"} ,
  {value: "KWD", label: "KW"} ,
  {value: "KYD", label: "KY"} ,
  {value: "KZT", label: "KZ"} ,
  {value: "LAK", label: "LA"} ,
  {value: "LBP", label: "LB"} ,
  {value: "LKR", label: "LK"} ,
  {value: "LRD", label: "LR"} ,
  {value: "LSL", label: "LS"} ,
  {value: "LTL", label: "LT"} ,
  {value: "LYD", label: "LY"} ,
  {value: "MAD", label: "MA"} ,
  {value: "MDL", label: "MD"} ,
  {value: "MGA", label: "MG"} ,
  {value: "MKD", label: "MK"} ,
  {value: "MMK", label: "MM"} ,
  {value: "MNT", label: "MN"} ,
  {value: "MOP", label: "MO"} ,
  {value: "MRO", label: "MR"} ,
  {value: "MUR", label: "MU"} ,
  {value: "MVR", label: "MV"} ,
  {value: "MWK", label: "MW"} ,
  {value: "MXN", label: "MX"} ,
  {value: "MYR", label: "MY"} ,
  {value: "MZN", label: "MZ"} ,
  {value: "NAD", label: "NA"} ,
  {value: "NGN", label: "NG"} ,
  {value: "NIO", label: "NI"} ,
  {value: "NOK", label: "NO"} ,
  {value: "NPR", label: "NP"} ,
  {value: "NZD", label: "NZ"} ,
  {value: "OMR", label: "OM"} ,
  {value: "PAB", label: "PA"} ,
  {value: "PEN", label: "PE"} ,
  {value: "PGK", label: "PG"} ,
  {value: "PHP", label: "PH"} ,
  {value: "PKR", label: "PK"} ,
  {value: "PLN", label: "PL"} ,
  {value: "PYG", label: "PY"} ,
  {value: "QAR", label: "QA"} ,
  {value: "RON", label: "RO"} ,
  {value: "RSD", label: "RS"} ,
  {value: "RUB", label: "RU"} ,
  {value: "RWF", label: "RW"} ,
  {value: "SAR", label: "SA"} ,
  {value: "SBD", label: "SB"} ,
  {value: "SCR", label: "SC"} ,
  {value: "SDG", label: "SD"} ,
  {value: "SEK", label: "SE"} ,
  {value: "SGD", label: "SG"} ,
  {value: "SHP", label: "SH"} ,
  {value: "SLL", label: "SL"} ,
  {value: "SOS", label: "SO"} ,
  {value: "SRD", label: "SR"} ,
  {value: "SSP", label: "SS"} ,
  {value: "STD", label: "ST"} ,
  {value: "SYP", label: "SY"} ,
  {value: "SZL", label: "SZ"} ,
  {value: "THB", label: "TH"} ,
  {value: "TJS", label: "TJ"} ,
  {value: "TMT", label: "TM"} ,
  {value: "TND", label: "TN"} ,
  {value: "TOP", label: "TO"} ,
  {value: "TRY", label: "TR"} ,
  {value: "TTD", label: "TT"} ,
  {value: "TWD", label: "TW"} ,
  {value: "TZS", label: "TZ"} ,
  {value: "UAH", label: "UA"} ,
  {value: "UGX", label: "UG"} ,
  {value: "USD", label: "US"} ,
  {value: "UYU", label: "UY"} ,
  {value: "UZS", label: "UZ"} ,
  {value: "VEF", label: "VE"} ,
  {value: "VND", label: "VN"} ,
  {value: "VUV", label: "VU"} ,
  {value: "WST", label: "WS"} ,
  {value: "XAF", label: "CF"} ,
  {value: "XOF", label: "BF"} ,
  {value: "XPF", label: "PF"} ,
  {value: "YER", label: "YE"} ,
  {value: "ZAR", label: "ZA"} ,
  {value: "ZMK", label: "ZM"} ,
  {value: "ZWL", label: "ZW"} ,
]